/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai4_th;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Ly_lich_sinh_vien extends javax.swing.JFrame {
    //Lưu dữ liệu
    ArrayList<SinhVien> lstSV = new ArrayList();
    String Hoten,Namsinh,Lop,MSSV;
    public Ly_lich_sinh_vien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmssv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txtnam = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        cblop = new javax.swing.JComboBox<>();
        btncong = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbsv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("MSSV");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, -1, -1));

        jLabel3.setText("Họ tên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 54, -1, -1));

        jLabel4.setText("Năm sinh");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 83, -1, -1));

        jLabel5.setText("Lớp");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 117, -1, -1));
        jPanel1.add(txtmssv, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 17, 122, -1));
        jPanel1.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 51, 122, -1));
        jPanel1.add(txtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 80, 120, -1));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel1.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 16, 80, -1));

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 50, 80, -1));

        btnsua.setText("Sửa/Lưu");
        jPanel1.add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 79, 80, -1));

        btntimkiem.setText("Tìm kiếm");
        jPanel1.add(btntimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 113, 80, -1));

        cblop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "57TH1", "57TH2", "58TH1", "58TH2", " " }));
        jPanel1.add(cblop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 79, -1));

        btncong.setText("...");
        jPanel1.add(btncong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 37, -1));

        tbsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MSSV", "Họ và tên", "Năm sinh", "Lớp"
            }
        ));
        jScrollPane2.setViewportView(tbsv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        //B1:Lấy data từ các control
        Hoten = txthoten.getText();
        Namsinh = txtnam.getText();
        Lop = cblop.getSelectedItem().toString();
        MSSV = txtmssv.getText();
        
        //B2:Đưa vào list SinhVien
        SinhVien sv=new SinhVien();
        sv.setMSSV(MSSV);
        sv.setHoTen(Hoten);
        sv.setNamsinh(Namsinh);
        sv.setLop(Lop);
        //Thêm vô ds
        lstSV.add(sv);
        
        //B3:Hiện lên JTable
        //1.Tạo mới để setModel
        DefaultTableModel model = new DefaultTableModel();
  
        //1.2.Đặt tên cho các cột
        model.addColumn("MSSV");
        model.addColumn("Họ tên");
        model.addColumn("Năm sinh");
        model.addColumn("Lớp");
        //2.Duyệt ArrayList để đưa vào Model
        for(int i=0; i<lstSV.size();i++)
        {
            SinhVien SV = lstSV.get(i);
            Vector<String> h=new Vector<>();
            h.add(SV.getMSSV());
            h.add(SV.getHoTen());
            h.add(SV.getNamsinh());
            h.add(SV.getLop());
            model.addRow(h);
        }
        //3.Hiện ra điều khiển
        tbsv.setModel(model);
        
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        //Chọn hàng cần xóa
        int hang=tbsv.getSelectedRow();
        //Hỏi xác nhận xóa
        int kq=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa", "Xác nhận", JOptionPane.WARNING_MESSAGE);
        if(kq==JOptionPane.YES_NO_OPTION)
            //Xóa khỏi List
            lstSV.remove(hang);
        //Cập nhật
        //1.Tạo mới để setModel
        DefaultTableModel model = new DefaultTableModel();
  
        //1.2.Đặt tên cho các cột
        model.addColumn("MSSV");
        model.addColumn("Họ tên");
        model.addColumn("Năm sinh");
        model.addColumn("Lớp");
        //2.Duyệt ArrayList để đưa vào Model
        for(int i=0; i<lstSV.size();i++)
        {
            SinhVien SV = lstSV.get(i);
            Vector<String> h=new Vector<>();
            h.add(SV.getMSSV());
            h.add(SV.getHoTen());
            h.add(SV.getNamsinh());
            h.add(SV.getLop());
            model.addRow(h);
        }
        //3.Hiện ra điều khiển
        tbsv.setModel(model);
    }//GEN-LAST:event_btnxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ly_lich_sinh_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ly_lich_sinh_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ly_lich_sinh_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ly_lich_sinh_vien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ly_lich_sinh_vien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncong;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cblop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbsv;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmssv;
    private javax.swing.JTextField txtnam;
    // End of variables declaration//GEN-END:variables
}
