/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3;


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author USER
 */
public class the_thao extends javax.swing.JFrame {

    /**
     * Creates new form the_thao
     */
    public the_thao() {
        initComponents();
    }
    DefaultListModel trai= new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsyeuthich = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsdsthethao = new javax.swing.JList<>();
        btnthem = new javax.swing.JButton();
        btnallphai = new javax.swing.JButton();
        btn1trai = new javax.swing.JButton();
        btn1phai = new javax.swing.JButton();
        btnalltrai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listview");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DS Môn Thể Thao");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Môn yêu thích");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jScrollPane1.setViewportView(lsyeuthich);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 110, -1));

        jScrollPane2.setViewportView(lsdsthethao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, -1));

        btnthem.setText("+");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        getContentPane().add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 40, -1));

        btnallphai.setText(">>");
        btnallphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallphaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnallphai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, -1));

        btn1trai.setText("<");
        getContentPane().add(btn1trai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 50, -1));

        btn1phai.setText(">");
        btn1phai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1phaiActionPerformed(evt);
            }
        });
        getContentPane().add(btn1phai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 50, -1));

        btnalltrai.setText("<<");
        getContentPane().add(btnalltrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        String dsTT = JOptionPane.showInputDialog(null, "Nhập môn thể thao", null, JOptionPane.PLAIN_MESSAGE);
        //Lấy từ model
        ListModel dstt= lsdsthethao.getModel();
        //Từ model chuyển sang mảng
        String [] tt = new String[dstt.getSize()+1];
        int i=0;
        for(i=0; i < dstt.getSize(); i++)
            tt[i] = dstt.getElementAt(i).toString();
        //Thêm vao cuối
        tt[i] = dsTT;
        //Cập nhật list
        lsdsthethao.setListData(tt);
    }//GEN-LAST:event_btnthemActionPerformed

    private void btn1phaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1phaiActionPerformed
            ListModel mTrai=lsdsthethao.getModel();
            ArrayList<String> arrTrai = new ArrayList<>();
            int a=0;
            for(a=0; a < mTrai.getSize(); a++)
            {
                String tr=mTrai.getElementAt(a).toString();
                arrTrai.add(tr);
            }
            //Lây vị trí được chọn
            int i=lsdsthethao.getSelectedIndex();
            String chon = arrTrai.get(i);
            //Xóa khỏi arrTrai
            arrTrai.remove(i);
            String[] dltrai = arrTrai.toArray(new String[0]);
            lsdsthethao.setListData(dltrai);
            
            //Thêm vô list môn yeu thích
            ListModel dstt= lsyeuthich.getModel();
            //Từ model chuyển sang mảng
            String [] tt = new String[dstt.getSize()+1];
            int j=0;
            for(j=0; j < dstt.getSize(); j++)
             tt[j] = dstt.getElementAt(i).toString();
            //Thêm vao cuối
            tt[j]=chon;
           //Cập nhật list
            lsyeuthich.setListData(tt);
    }//GEN-LAST:event_btn1phaiActionPerformed

    private void btnallphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallphaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnallphaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(the_thao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(the_thao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(the_thao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(the_thao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new the_thao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1phai;
    private javax.swing.JButton btn1trai;
    private javax.swing.JButton btnallphai;
    private javax.swing.JButton btnalltrai;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lsdsthethao;
    private javax.swing.JList<String> lsyeuthich;
    // End of variables declaration//GEN-END:variables
}
